version: "3.8"
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile # Assuming your Dockerfile is named 'Dockerfile'
    ports:
      - "4300:80" # Map host port 8080 to container port 80
    restart: always # Optional: Restart the container if it stops
